apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-record-ui-app
  namespace: student-record-ui-app
spec:
  project: default

  source:
    repoURL: https://github.com/yaredgh/Student-Record-Ui-app.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: student-record-ui-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
