version: "3"

services:
  studentapp:
    image: akashkale/springboot-app
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/studentdatadb?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQLDB_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:

    container_name: mysqldb
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQLDB_USER=${MYSQLDB_USER}
      - MYSQLDB_ROOT_PASSWORD =${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  mysql-data:
