version: "3"

services:
  studentapp:
    image: akashkale/springboot-app
    build: .
    ports:
      - "8081:8080"
    environment:
      MYSQL_HOST: studentdatadb
      MYSQL_USER: root
      MYSQL_PASSWORD: Yafet@2023
      MYSQL_PORT: 3306
#      need to chage the db to my continer db mysqldb
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/studentdatadb?serverTimezone=America/New_York
    depends_on:
     - mysqldb

  mysqldb:
     container_name: studentdatadb
     image: mysql
     ports:
     - "3306"
     environment:
       MYDQL_DATABASE: studentdatadb
       MYSQL_ROOT_PASSWORD: Yafet@2023

