#version: "3"
#
#services:
#  studentapp:
#    image: akashkale/springboot-app
#    build: .
#    ports:
#      - "8081:8080"
#    depends_on:
#      - mysqldb
#
#  mysqldb:
#    container_name: studentdatadb
#    image: mysql:8
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql-data:/var/lib/mysql
#
#volumes:
#  mysql-data:
